# Generated by Django 6.0.3 on 2026-03-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('anomaly', models.IntegerField(default=0)),
                ('severity', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'logs_logentry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
